//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto03_Identity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Navegacao
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Acao { get; set; }
        public Nullable<int> IdAcao { get; set; }
    }
}
